# -*- coding: utf-8 -*-
"""git1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KWKLzjgVFs4eVfY1t7LImom5JmDRQoST
"""

def wishsomeone():
  print('Hi, Hello !!')

